### PR TITLE
Make __toString() compatible with throwing

### LINKED ISSUE #142: Response::__toString() should not hide exception
https://github.com/Nyholm/psr7/blob/d38874cbc289d25a309cefd04379e24352ced608/src/Stream.php#L98-L109

I found this because of https://github.com/php-http/client-common/issues/186
In my application, I had a 200 with an empty body :exploding_head: 

IMHO, doing this is wrong as it hides the root cause.

More over, in PHP 7.4 it's allowed to throw exception.
And for PHP 7.3-, it prefer a fatal error than something wrong.

WDYT?

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #142

On PHP 7.4, `__toString()` can throw.
And before PHP  7.4, `__toString()` can throw also, when the Symfony ErrorHandler is used: https://github.com/symfony/symfony/blob/e46495499841f805ab1915643f763d736d24822e/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L498-L503

This fixes tests meanwhile.

### CODE REVIEW

File: src/Stream.php [hunk 1]
```diff
@@ -95,15 +97,31 @@ public function __destruct()
         $this->close();
     }
 
-    public function __toString(): string
+    /**
+     * @return string
```
Comment (nicolas-grekas) [inline src/Stream.php:101]: this is required to allow Symfony's error handler to work effectively.

**Comment by Nyholm** [comment]
Do you mind rebasing this PR?

**Comment by nicolas-grekas** [comment]
Thank you for merging!
